LRQA-66587
thaisfrota/liferay-portal pull request #2
Opened 2021-04-16 16:06 UTC by thaisfrota

[LRQA-66587](https://issues.liferay.com/browse/LRQA-66587)

2021-04-16 16:06 UTC, thaisfrota commented
ci:test:sf

2021-04-23 12:55 UTC, emanuelfisilva reviewed
edit: please address inline requests

2021-04-23 12:55 UTC, emanuelfisilva commented
ci:test:sf

2021-04-23 13:05 UTC, emanuelfisilva commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/wem/translations/LocalizedSimpleFieldsStructure.testcase
> +		WebContentStructures.addCP(structureName = "WC Structure Title");
@thaisfrota please, add the `property portal.acceptance = "true";`

2021-04-23 13:06 UTC, emanuelfisilva commented on modules/apps/data-engine/data-engine-test/src/testFunctional/tests/wem/translations/LocalizedSimpleFieldsStructure.testcase
> +		ApplicationsMenu.gotoPortlet(
@thaisfrota please, add the property portal.acceptance = "true";

2021-04-23 13:06 UTC, emanuelfisilva requested changes
Please, see my inline requests. Thanks

2021-04-23 14:34 UTC, emanuelfisilva commented
Thanks @thaisfrota . Made the changes and forwarded: https://github.com/emanuelfisilva/liferay-portal/pull/151

2021-04-23 14:34 UTC, closed without merging