LRQA-66584
thaisfrota/liferay-portal pull request #5
Opened 2021-04-26 16:34 UTC by thaisfrota

2021-04-26 16:35 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-04-26 16:39 UTC, thaisfrota commented
ci:test:sf

2021-04-26 16:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-18.liferay.com/job/test-portal-source-format/5581/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-18.liferay.com//userContent/jobs/test-portal-source-format/builds/5581/jenkins-report.html">here</a>.</b></p>

2021-04-26 16:43 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b696cae1492d252d0154f8658bcc5a41234c4c0f">b696cae1492d252d0154f8658bcc5a41234c4c0f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/thaisfrota/liferay-portal/tree/LRQA-66584">LRQA-66584</a><br/>Branch GIT ID: <a href="https://github.com/thaisfrota/liferay-portal/commit/cbf4d4103d6cfc1ff588022b84d74c01205a37d9">cbf4d4103d6cfc1ff588022b84d74c01205a37d9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-source-format/5581/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/5581/jenkins-report.html">here</a>.</h5></details></html>

2021-04-26 16:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-18.liferay.com/job/test-portal-source-format/5581/">test-portal-source-format#5581</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-18.liferay.com/userContent/jobs/test-portal-source-format/builds/5581/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/thaisfrota/liferay-portal/pull/5">thaisfrota#5</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1528598335">[master] ci:test:sf - thaisfrota &gt; thaisfrota - PR#5 - 2021-04-26[09:40:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-18.liferay.com/job/publish-testray-report/487/">publish-testray-report#487</a><br/></div></div>

2021-04-27 21:24 UTC, emanuelfisilva requested changes
Please see my changes: https://github.com/emanuelfisilva/liferay-portal/pull/153

2021-04-27 21:24 UTC, emanuelfisilva commented
Thanks @thaisfrota !
Forwarded: https://github.com/emanuelfisilva/liferay-portal/pull/153

2021-04-27 21:24 UTC, closed without merging